############### 服务器设置 ###############
#服务器IP
serverIP: "127.0.0.1"

#服务器端口，默认 38440
serverPort: 38440

#服务器名称
serverName: "Bukkit"

#服务器身份
#生成器： https://1024tools.com/uuid https://www.uuidgenerator.net/
ID: "00000000-0000-0000-0000-000000000000"

#-----------开发设置----------#
#！！！非必要请勿改动！！！
#服务器心跳速度（秒）
#需要与PHP服务器的心跳同时修改
serverPulse: 20

############### 扩展插件 ##################
#是否使用VexView插件来显示图片
#需要付费版的VexView才能使用
useVexView: false

#收到图片时显示在屏幕的位置x
#需要VexView插件支持
#这个值需要在0和1之间，它是你屏幕从左到右的百分比宽度
imageX: 0.68

#收到图片时显示在屏幕的位置y
#需要VexView插件支持
#这个值需要在0和1之间，它是你屏幕从上到下的百分比高度
imageY: 0.65

#图片过大时压缩到多少像素点（x）
imageBigX: 65

#图片过大时压缩到多少像素点（y）
imageBigY: 65

############### 聊天设置 ##################
# %world% 表示来自哪个世界或哪个群
# %player% 表示说话的玩家

#收到的信息在MC中的聊天前缀
messageFormQQ: "[%world%]<%player%> "

